data_dir: <path_to_root>/MGNN/data/seed_81
exp_dir:  <path_to_root>/MGNN/experiments
use_dummy_constants: false   # options: true | false
encoding_scheme: canonical # options: iclr22 | canonical
num_layers : 2  # options 1|2|3
aggregations: [max, max]    # one entry per layer specified options:max|sum
derivation_threshold: 0.0001
non_negative_weights: true       # options: true | false
clamping: 0 
target_predicate: positive # options: positive|null # for ADNI this is the predcate that the loss and explanations should be restricted to. Null otherwise
learning_rate: 0.001 # set to 0.01 to match with ICLR22 paper is too high for ADNI data
early_stopping_lag: 200 # num epochs to see without any improvement in loss before stopping training