data_dir: /Users/reubenmatthew/Documents/Royal Holloway/Dissertation/mgnns/data/link_prediction/WN18RRv1
exp_dir:  /Users/reubenmatthew/Documents/Royal Holloway/Dissertation/mgnns/experiments
use_dummy_constants: false   # options: true | false
encoding_scheme: iclr22 # options: iclr22 | canonical
num_layers : 2  # options 1|2|3
aggregations: [max, max]    # one entry per layer specified options:max|sum
derivation_threshold: 0.0001
non_negative_weights: true       # options: true | false
clamping: 0 
target_predicate: postive # for ADNI this is the predcate that the loss and explanations should be restricted to. Null otherwise
